name: SonarQube Analysis

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      - run: flutter --version

      - name: Install packages
        run: flutter pub get


      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Add Flutter to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH


      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.projectKey=mariam2MOHMED_Fitness-App
            -Dsonar.sources=lib/features,pubspec.yaml
            -Dsonar.dart.analyzer.mode=FLUTTER
            -Dsonar.branch.name=main
            -Dsonar.exclusions=/.g.dart,/.freezed.dart,/*.config.dart 
            -Dsonar.coverage.exclusions=/.g.dart,/.freezed.dart,/*.config.dart
            -Dsonar.dart.lcov.reportPaths=coverage/lcov.info


      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@master
        continue-on-error: true
        id: quality-gate-check
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}